import { NavMenu } from "@app/shared/types/nav-menu.interface";

const dashboard: NavMenu[] = [
  {
    path: "/dashboard",
    title: "Dashboard",
    translateKey: "NAV.DASHBOARD",
    type: "item",
    iconType: "feather",
    icon: "icon-home",
    key: "dashboard",
    submenu: [],
    claims: ["DASHBOARD_VIEW_DASHBOARD"],
  },
];

const apps: NavMenu[] = [
  {
    path: "",
    title: "Apps",
    translateKey: "NAV.APPS",
    type: "title",
    iconType: "feather",
    icon: "icon-grid",
    key: "apps",
    claims: [
      "REMINDER_VIEW_REMINDERS",
      "ARTICLE_VIEW_ARTICLES",
      "CHAT_VIEW_CHATS",
      "LOGIN_AUDIT_VIEW_LOGIN_AUDIT_LOGS",
      "FORUM_VIEW_FORUMS",
      "ARTICLE_VIEW_ARTICLES",
      "BLOG_VIEW_BLOGS",
      "SURVEY_VIEW_SURVEYS",
    ],
    submenu: [
      {
        path: "/apps/chat",
        title: "Chat",
        translateKey: "NAV.APPS_CHAT",
        type: "item",
        iconType: "feather",
        icon: "icon-message-circle",
        key: "apps.chat",
        claims: ["CHAT_VIEW_CHATS"],
        submenu: [],
      },
      {
        path: "/apps/calendar",
        title: "Calendar",
        translateKey: "NAV.APPS_CALENDAR",
        type: "item",
        iconType: "feather",
        icon: "icon-calendar",
        key: "apps.calendar",
        claims: ["REMINDER_VIEW_REMINDERS"],
        submenu: [],
      },
      {
        path: "/apps/logins",
        title: "Login audits",
        translateKey: "NAV.APPS_LOGINS",
        type: "item",
        iconType: "feather",
        icon: "icon-log-in",
        key: "apps.login",
        claims: ["LOGIN_AUDIT_VIEW_LOGIN_AUDIT_LOGS"],
        submenu: [],
      },
      {
        path: "/apps/response-audits",
        title: "Response audits",
        translateKey: "NAV.APPS_RESPONSES_AUDITS",
        type: "item",
        iconType: "feather",
        icon: "icon-message-square",
        key: "apps.response-audits",
        claims: ["RESPONSE_AUDIT_TRAIL_VIEW_RESPONSE_AUDIT_TRAIL"],
        submenu: [],
      },
      {
        path: "",
        title: "Articles",
        translateKey: "NAV.APPS_ARTICLE",
        type: "title",
        iconType: "line-awesome",
        icon: "la-newspaper",
        key: "apps.articles",
        claims: ["ARTICLE_VIEW_ARTICLES", "ARTICLE_VIEW_CATEGORIES"],
        submenu: [
          {
            path: "/apps/articles",
            title: "List",
            translateKey: "NAV.APPS_ARTICLE_LIST",
            type: "item",
            iconType: "line-awesome",
            icon: "la-newspaper",
            key: "apps.articles.list",
            claims: ["ARTICLE_VIEW_ARTICLES"],
            submenu: [],
          },
          {
            path: "/apps/articles/categories",
            title: "Categories",
            translateKey: "NAV.APPS_ARTICLE_CATEGORY",
            type: "item",
            iconType: "line-awesome",
            icon: "la-newspaper",
            key: "apps.articles.category",
            claims: ["ARTICLE_VIEW_CATEGORIES"],
            submenu: [],
          },
        ],
      },
      {
        path: "",
        title: "Blogs",
        translateKey: "NAV.APPS_BLOG",
        type: "item",
        iconType: "feather",
        icon: "icon-bold",
        key: "apps.blogs",
        claims: ["BLOG_VIEW_BLOGS", "BLOG_VIEW_CATEGORIES"],
        submenu: [
          {
            path: "/apps/blogs",
            title: "List",
            translateKey: "NAV.APPS_BLOG_LIST",
            type: "item",
            iconType: "line-awesome",
            icon: "la-newspaper",
            key: "apps.blogs.list",
            claims: ["BLOG_VIEW_BLOGS"],
            submenu: [],
          },
          {
            path: "/apps/blogs/categories",
            title: "Categories",
            translateKey: "NAV.APPS_BLOG_CATEGORY",
            type: "item",
            iconType: "line-awesome",
            icon: "la-newspaper",
            key: "apps.blogs.categories",
            claims: ["BLOG_VIEW_CATEGORIES"],
            submenu: [],
          },
        ],
      },
      {
        path: "",
        title: "Forums",
        translateKey: "NAV.APPS_FORUM",
        type: "item",
        iconType: "feather",
        icon: "icon-feather",
        key: "apps.forums",
        claims: ["FORUM_VIEW_FORUMS"],
        submenu: [
          {
            path: "/apps/forums",
            title: "List",
            translateKey: "NAV.APPS_FORUM_LIST",
            type: "item",
            iconType: "line-awesome",
            icon: "la-newspaper",
            key: "apps.forums.list",
            claims: ["FORUM_VIEW_FORUMS"],
            submenu: [],
          },
          {
            path: "/apps/forums/categories",
            title: "Categories",
            translateKey: "NAV.APPS_FORUM_CATEGORY",
            type: "item",
            iconType: "line-awesome",
            icon: "la-newspaper",
            key: "apps.forums.categories",
            claims: ["FORUM_VIEW_CATEGORIES"],
            submenu: [],
          },
        ],
      },
      {
        path: "/apps/surveys",
        title: "Surveys",
        translateKey: "NAV.APPS_SURVEY",
        type: "item",
        iconType: "feather",
        icon: "icon-star",
        key: "apps.surveys.list",
        claims: ["SURVEY_VIEW_SURVEYS"],
        submenu: [],
      },
    ],
  },
];

const documents: NavMenu[] = [
  {
    path: "document",
    title: "Documents",
    translateKey: "NAV.DOCUMENT",
    type: "title",
    iconType: "feather",
    icon: "icon-grid",
    key: "documents",
    claims: ["ALL_DOCUMENTS_VIEW_DOCUMENTS", "show"],
    submenu: [
      {
        path: "/document/list",
        title: "Documents",
        translateKey: "NAV.DOCUMENT_ALL",
        type: "item",
        iconType: "feather",
        icon: "icon-file",
        key: "documents.all",
        claims: ["ALL_DOCUMENTS_VIEW_DOCUMENTS"],
        submenu: [],
      },
      {
        path: "/document/assigned",
        title: "Assigned documents",
        translateKey: "NAV.DOCUMENT_ASSIGNED",
        type: "item",
        iconType: "feather",
        icon: "icon-file-text",
        key: "documents.assigned-documents",
        claims: ["show"],
        submenu: [],
      },
      {
        path: "/document/categories",
        title: "Document categories",
        translateKey: "NAV.DOCUMENT_CATEGORIES",
        type: "item",
        iconType: "feather",
        icon: "icon-folder",
        key: "documents.documents-categories",
        claims: ["DOCUMENT_CATEGORY_MANAGE_DOCUMENT_CATEGORY"],
        submenu: [],
      },
      {
        path: "/document/audit",
        title: "Document audit trails",
        translateKey: "NAV.DOCUMENT_AUDIT_TRAIL",
        type: "item",
        iconType: "feather",
        icon: "icon-calendar",
        key: "documents.documents-audit",
        claims: ["DOCUMENT_AUDIT_TRAIL_VIEW_DOCUMENT_AUDIT_TRAIL"],
        submenu: [],
      },
    ],
  },
];

const users: NavMenu[] = [
  {
    path: "user",
    title: "Users",
    translateKey: "NAV.USERS",
    type: "title",
    iconType: "feather",
    icon: "icon-grid",
    key: "users",
    claims: ["USER_VIEW_USERS", "ROLE_VIEW_ROLES", "USER_ASSIGN_USER_ROLE"],
    submenu: [
      {
        path: "/user/list",
        title: "Users",
        translateKey: "NAV.USERS_LIST",
        type: "item",
        iconType: "feather",
        icon: "icon-users",
        key: "users.list",
        claims: ["USER_VIEW_USERS"],
        submenu: [],
      },
      {
        path: "/user/role",
        title: "Roles",
        translateKey: "NAV.USERS_ROLES_LIST",
        type: "item",
        iconType: "feather",
        icon: "icon-shield",
        key: "users.roles",
        claims: ["ROLE_VIEW_ROLES"],
        submenu: [],
      },
      {
        path: "/user/user-roles",
        title: "User Roles",
        translateKey: "NAV.USER_ROLES",
        type: "item",
        iconType: "feather",
        icon: "icon-users",
        key: "users.user-roles",
        claims: ["USER_ASSIGN_USER_ROLE"],
        submenu: [],
      },
    ],
  },
];

export const navConfiguration: NavMenu[] = [
  ...dashboard,
  ...documents,
  ...apps,
  ...users,
];
